import type { Metadata } from "next";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Utsav Joshi",
  description: "Generated by create next app",
};

/**
 * Root layout component for the application.
 *
 * @param props - The properties for the component.
 * @param props.children - The child components to render.
 * @returns The root layout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
=======
 * RootLayout is a strongly typed layout component for Next.js apps.
 *
 * @param {Object} props - The component props.
 * @param {React.ReactNode} props.children - The child components.
 * @return {React.ReactElement} The rendered layout.
 */
export default function RootLayout({children}: {children: React.ReactNode}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/logo.png" />
      </head>
      <body className={raleway.className}>
        <>
          {children}
          <Analytics />
          <SpeedInsights />
        </>
      </body>
    </html>
  );
}
