export const siteConfig = {
  name: "Utsav Joshi",
  description:
    "Utsav Joshi | Software Engineer | Full-Stack Developer specializing in React, Next.js, and modern web technologies.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.joshiutsav.com",
  ogImage: `${process.env.NEXT_PUBLIC_SITE_URL || "https://www.joshiutsav.com"}/og-image.jpg`,
  author: "Utsav Joshi",
  email: "hi@joshiutsav.com",
  twitterHandle: "@utsavjosh1",
  keywords: [
    "developer",
    "portfolio",
    "web development",
    "React",
    "Next.js",
    "full-stack",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "REST API",
    "GraphQL",
    "Docker",
    "Utsav Joshi",
    "joshiutsav",
    "utsavjoshi",
    "Utsav Joshi software engineer",
    "Utsav Joshi portfolio",
    "joshiutsav.com",
    "hire Utsav Joshi",

    "software engineer",
    "full stack developer",
    "senior software developer",
    "web developer",
    "frontend developer",
    "backend developer",
    "JavaScript developer",
    "TypeScript developer",
    "React developer",
    "Node.js developer",

    "React specialist",
    "Next.js developer",
    "TypeScript expert",
    "JavaScript expert",
    "Node.js specialist",
    "Express.js developer",
    "MongoDB developer",
    "PostgreSQL developer",
    "REST API developer",
    "GraphQL developer",

    "custom web development",
    "web application development",
    "responsive web design",
    "mobile app development",
    "API development services",
    "database design",
    "cloud solutions",
    "software architecture",
    "code optimization",
    "performance tuning",

    "experienced React developer for hire",
    "senior full stack JavaScript engineer",
    "professional TypeScript Next.js developer",
    "custom software development services",
    "modern web application architect",
    "scalable frontend solutions",
    "enterprise web development",
    "freelance software engineer",
    "contract developer",
    "remote software developer",

    "convert design to code",
    "website redesign developer",
    "legacy system modernization",
    "web performance optimization",
    "mobile-first development",
    "cross-browser compatibility",
    "SEO-friendly development",
    "accessibility compliance",
    "secure web applications",
    "user experience optimization",

    "fintech developer",
    "e-commerce developer",
    "SaaS application developer",
    "startup technical consultant",
    "enterprise software solutions",
    "healthcare software developer",
    "education platform developer",
    "real estate web applications",

    "agile development",
    "test-driven development",
    "clean code practices",
    "microservices architecture",
    "serverless development",
    "DevOps integration",
    "CI/CD pipeline setup",
    "code review specialist",

    "hire experienced developer",
    "freelance web developer",
    "contract software engineer",
    "remote React developer",
    "full-time developer available",
    "part-time development services",
    "technical consultation services",
    "code audit services",

    "software developer India",
    "remote developer worldwide",
    "global software engineer",
    "international web developer",

    "soft skills",
    "qualities",
    "reliable software engineer",
    "communicative developer",
    "deadline-driven programmer",
    "collaborative team player",
    "innovative problem solver",
    "detail-oriented developer",
    "client-focused engineer",
    "results-driven programmer",
  ],
  links: {
    twitter: "https://twitter.com/utsavjosh1",
    github: "https://github.com/utsavjosh1",
    linkedin: "https://www.linkedin.com/in/utsavjosh1/",
    email: "hi@joshiutsav.com",
  },
  location: {
    city: "New Delhi",
    region: "Delhi",
    country: "India",
    postalCode: "110018",
  },
};
